# Aplicacion
spring.application.name=piali
server.port=${PORT:8080}
server.servlet.context-path=/api/v1

# Base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Jackson
spring.jackson.default-property-inclusion=non_null

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Logging
logging.level.root=INFO
logging.level.com.tuempresa.piali=DEBUG

# CORS
#app.core.allowed-origins=${app.allowed-origins:http://localhost:8080}
app.core.allowed-origins=http://localhost:3000

# Data Initializer
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
